# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\importmapimgdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportMapImgDialog(object):
    def setupUi(self, ImportMapImgDialog):
        ImportMapImgDialog.setObjectName("ImportMapImgDialog")
        ImportMapImgDialog.setEnabled(True)
        ImportMapImgDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportMapImgDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ImportMapImgDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridWidget = QtWidgets.QWidget(ImportMapImgDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridWidget.sizePolicy().hasHeightForWidth())
        self.gridWidget.setSizePolicy(sizePolicy)
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.select_file_button = QtWidgets.QPushButton(self.gridWidget)
        self.select_file_button.setObjectName("select_file_button")
        self.gridLayout.addWidget(self.select_file_button, 0, 0, 1, 1)
        self.file_dir_line = QtWidgets.QLineEdit(self.gridWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_dir_line.sizePolicy().hasHeightForWidth())
        self.file_dir_line.setSizePolicy(sizePolicy)
        self.file_dir_line.setMinimumSize(QtCore.QSize(300, 0))
        self.file_dir_line.setObjectName("file_dir_line")
        self.gridLayout.addWidget(self.file_dir_line, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.gridWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(ImportMapImgDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ImportMapImgDialog)
        self.buttonBox.accepted.connect(ImportMapImgDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImportMapImgDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImportMapImgDialog)

    def retranslateUi(self, ImportMapImgDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportMapImgDialog.setWindowTitle(_translate("ImportMapImgDialog", "导入地图图片"))
        self.label.setText(_translate("ImportMapImgDialog", "请选择地图图片文件位置"))
        self.select_file_button.setText(_translate("ImportMapImgDialog", "选择文件"))
        self.file_dir_line.setPlaceholderText(_translate("ImportMapImgDialog", "文件路径"))
